### ISSUE TITLE
does Canada support Phoenix Channels?

### ISSUE THREAD

**Issue by niccolox** [jarednorman/canada#14]
is this even a question ?

apologies, am just learning about the Channels vs Resources Phoenix issue

**Comment by jarednorman** [comment]
Canada has doesn't care what your resources are. It can be used for anything. Perhaps you should also take a look at [Canary](https://hex.pm/packages/canary).

**Comment by niccolox** [comment]
hi, thanks, am using Canary and Canada and will ask the question there...
