### ISSUE TITLE
HEX Package

### ISSUE THREAD

**Issue by slashmili** [jarednorman/canada#19]
Hi!

I can see Elixir 1.4 warnings are fixed in this commit ef0705c1a8b53fe1e8a9e1d2c4812e697e7e41f8 but the version hasn't changed yet in `mix.exs` and Hex.

Could you update the package in HEX?

**Comment by yordis** [comment]
@jarednorman does this still valid?

**Comment by jarednorman** [comment]
Probably. This project really only gets updated to fix language compat issues and has never had a breaking change, so it's totally safe to point at the GitHub repo instead of Hex for this. At some point I'll get around to pushing up a fresh version though.

**Comment by yordis** [comment]
@jarednorman but why you don't push a minor release to Hex? 😢

**Comment by jarednorman** [comment]
I'm busy. I don't even have Elixir installed on my computer.

**Comment by jarednorman** [comment]
New release cut! Sorry for the delays!

**Comment by slashmili** [comment]
@jarednorman Thanks!

BTW we understand if you are busy or you don't have the setup to make the release.

It would be great if you grant me access to make the releases now and then. my hex account is [slashmili](https://hex.pm/users/slashmili)

**Comment by jarednorman** [comment]
I'm all setup now, so this shouldn't be a problem, but if it does become a problem again I will keep you in mind. :smiley:
