### ISSUE TITLE
Compile warnings for elixir 1.4 

### ISSUE THREAD

**Issue by developerworks** [jarednorman/canada#20]
```
warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name

```

**Comment by niahoo** [comment]
When elixir fights it's own lame syntax choices.

**Comment by yordis** [comment]
Related to #19

**Comment by yordis** [comment]
@jarednorman would you take into consideration to `release` a patch version or update the `README` to use `master` branch?

**Comment by OvermindDL1** [comment]
Or pass off ownership?  I'd be up for keeping it up to date.

**Comment by jarednorman** [comment]
New release cut! Sorry for the delays!
