### ISSUE TITLE
Docs for can?/3

### ISSUE THREAD

**Issue by spapas** [jarednorman/canada#27]
Hello, sometimes the macro `can?/2` does not work properly for example when the  method is a variable. Thus, something like this won't work:

```
import Canada, only: [can?: 2]

method = action_name(conn)
if %User{} |> can?(method(Authority)) do
```

However, I was able to make it work using the function `can?/3` like this:

```
import Canada.Can, only: [can?: 3]

method = action_name(conn)
if %User{} |> can?(method, Authority) do
```

The thing is that I had to check out the source code of the library myself to find out of this; I propose adding a small section in the docs describing `can?/3`.

TIA

**Comment by jarednorman** [comment]
Ah, I see. You're dynamically deciding on the action you want to authorize. Rather than forcing people to use the protocol directly, it's probably worth providing `can?/3` function on the `Canada` module that just wraps a call to the protocol.

Thanks for bringing this up.
