### ISSUE TITLE
Elixir version too restrictive

### ISSUE THREAD

**Issue by bencates** [jarednorman/canada#4]
The Elixir version constraint [here](https://github.com/jarednorman/canada/blob/master/mix.exs#L7) throws warnings in Elixir 1.1.0.  The constraint should probably be `"~> 1.0"`.

**Comment by follmann** [comment]
+1

**Comment by jarednorman** [comment]
Pull requests accepted. As are new maintainers. I'm not actively doing any Elixir development.
