### ISSUE TITLE
`canada` elixir version too restricted in hex.pm

### ISSUE THREAD

**Issue by OvermindDL1** [jarednorman/canada#8]
The version needs to be bumped (1.0.1 perhaps?) and uploaded to hex.pm to add support for the more relaxed Elixir version requirement.

If you are still no longer doing Elixir dev then I could take over this library if you wished to add me to the package handling on hex.pm so I could take over package pushing?

**Comment by OvermindDL1** [comment]
Any chance on resubmitting to hex.pm as a new version yet?  I cannot link to a git project, only hex, from my network.  ^.^

**Comment by schneidmaster** [comment]
:+1: also dealing w/this. Just a warning, not an error, but still annoying. Also consider using `>= 1.0` rather than `~> 1.0` unless there's some reason it won't work with higher versions (I'm using with 1.3.1 and it seems fine).

**Comment by jarednorman** [comment]
Yeah, it's fixed it master, I just need to roll a new release. In the meantime, point it at the GitHub if you can.

**Comment by OvermindDL1** [comment]
Unfortunately I cannot point it to the git repo because of work-network-related reasons.  ^.^

**Comment by jarednorman** [comment]
Not even over https?

**Comment by OvermindDL1** [comment]
Nope, hex.pm is being cached for versions, it does not know how to do that for git.

**Comment by jeffdeville** [comment]
I see the mix file's been updated, but I assume you'll need to bump the version for hex to pick up the change.

**Comment by clessg** [comment]
Any progress on this?

**Comment by jarednorman** [comment]
Sorry, I will try to cut a new version tonight. Reminder that unless you're in a weird restrictive network situation, there's no reason you can't just point your dependency at GitHub.

**Comment by OvermindDL1** [comment]
If you are not doing Elixir anymore any chance on passing the hex.pm management to another use?

**Comment by jarednorman** [comment]
I would grant another user access if someone is interested.

**Comment by jeffdeville** [comment]
My organization has offered to pick this up.  We coordinate the elixir meetups in philadelphia.  promptworks.com.  Let me know what info you need for the transfer.

**Comment by jeffdeville** [comment]
@jarednorman, if you'd like us to take care of it, our hex username is promptworks  Thanks for the work on this project. I've enjoyed it.

**Comment by OvermindDL1** [comment]
I'd be up for @jeffdeville to take it up, if otherwise he cannot then I'd be happy to, I already have a few things on hex as well.

**Comment by jarednorman** [comment]
@jeffdeville I appreciate it! I'll have to get Elixir set up to give you access to it on hex (I don't think they have a way to do it through the web.) I'll try to find time this weekend to do that, and give you access to the repo too. If I haven't done it by Monday, just shoot me a message to remind me.

**Comment by jeffdeville** [comment]
@jarednorman I just forked the repo actually. 1 less step. :-)

**Comment by jarednorman** [comment]
@jeffdeville I intend this to remain as the main repo. You'll need collab access to merge things.

**Comment by jeffdeville** [comment]
@jarednorman That's fine, you asked me to ping you if you hadn't gotten around to transferring the hex creds.  Ping. :-)

**Comment by slashmili** [comment]
@jarednorman @effdeville any update on this?

**Comment by jarednorman** [comment]
Nope. But I haven't forgotten about it.

**Comment by jarednorman** [comment]
[A glorious release is upon us!!!](https://hex.pm/packages/canada/1.0.1)

:tada::tada::tada::tada::tada:

Thanks to everyone who nagged me to eventually install Elixir and cut that release.
